const ADMIN_URL='https://oansbivjkczjbtxaknks.supabase.co';
const ADMIN_KEY='sb_publishable_9tDZPZ9KmCjHZqVXBmO-1g_8Aqpu8qE';
const adminDb=window.supabase.createClient(ADMIN_URL,ADMIN_KEY);
const admin$=s=>document.querySelector(s);
const adminMoney=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const adminEsc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
let adminUser=null,adminIsAdmin=false;
function notifyAdmin(t){if(typeof toast==='function')toast(t)}
async function checkAdmin(){if(window.serverSession&&window.serverFetch&&window.serverSession.role==='admin'){adminIsAdmin=true;adminUser={email:window.serverSession.email};showAdminContent();return true}const {data}=await adminDb.auth.getSession();adminUser=data.session?.user||null;if(!adminUser){adminIsAdmin=false;showAdminGate();return false}const {data:profile}=await adminDb.from('profiles').select('role').eq('id',adminUser.id).maybeSingle();adminIsAdmin=profile?.role==='admin';if(adminIsAdmin)showAdminContent();else showAdminGate();return adminIsAdmin}
function showAdminGate(){admin$('#adminNavBtn')?.classList.add('hidden');admin$('#adminContent')?.classList.add('hidden');admin$('#adminGate')?.classList.remove('hidden')}
function showAdminContent(){admin$('#adminNavBtn')?.classList.remove('hidden');admin$('#adminGate')?.classList.add('hidden');admin$('#adminContent')?.classList.remove('hidden')}
function periodStart(){const v=admin$('#adminPeriod').value;if(v==='all')return null;const d=new Date();d.setDate(d.getDate()-Number(v)+1);d.setHours(0,0,0,0);return d.toISOString()}
async function loadCommissionSetting(){if(!adminIsAdmin)return;const {data,error}=await adminDb.from('platform_settings').select('default_commission_rate').eq('id',true).maybeSingle();if(error){console.error('commission setting load failed',error);return}if(data?.default_commission_rate!=null){admin$('#defaultCommission').value=String(Number(data.default_commission_rate))}}
async function loadAdminStats(){if(!adminIsAdmin)return;if(window.serverSession&&window.serverFetch&&window.serverSession.role==='admin'&&!adminUser?.id){try{const [p,c]=await Promise.all([window.serverFetch('/admin/payouts?limit=100'),window.serverFetch('/admin/commission')]);admin$('#adminStats').innerHTML='<div class="admin-stat-card"><strong>'+adminMoney((p.payouts||[]).filter(x=>x.status==='pending').reduce((s,x)=>s+Number(x.net_amount||0),0))+'</strong><span>Offene Auszahlungen</span></div><div class="admin-stat-card"><strong>'+Number(c.rate).toFixed(1)+' %</strong><span>Provision</span></div>';admin$('#payoutTable').innerHTML=(p.payouts||[]).map(x=>'<div class="admin-table-row"><div><strong>'+adminEsc(x.merchant_name||'Händler')+'</strong><span>'+new Date(x.created_at).toLocaleDateString('de-DE')+' · '+x.order_count+' Bestellungen</span></div><div><strong>'+adminMoney(x.net_amount)+'</strong><small>'+adminEsc(x.status)+'</small></div></div>').join('')||'<p class="muted">Noch keine Auszahlungen.</p>';admin$('#adminSystem').innerHTML='<div><span>Angemeldet</span><strong>'+adminEsc(adminUser.email||'')+'</strong></div><div><span>Admin</span><strong>Self-hosted</strong></div>';return}catch(e){notifyAdmin(e.message||'Self-hosted Admindaten konnten nicht geladen werden');return}}const start=periodStart();const [{data:stats,error:statsErr},{data:merchants,error:merchantErr},{data:orders,error:orderErr},{data:payouts,error:payoutErr}]=await Promise.all([adminDb.rpc('admin_dashboard_stats',{p_start:start}),adminDb.rpc('admin_merchants',{p_start:start}),adminDb.rpc('admin_orders',{p_start:start}),adminDb.rpc('admin_payouts',{p_start:start})]);if(statsErr){notifyAdmin(statsErr.message);return}if(merchantErr||orderErr||payoutErr){notifyAdmin((merchantErr||orderErr||payoutErr).message);return}await loadCommissionSetting();const s=stats||{};admin$('#adminStats').innerHTML=`<div class="admin-stat-card"><strong>${s.users||0}</strong><span>Registrierte Nutzer</span></div><div class="admin-stat-card"><strong>${s.merchants||0}</strong><span>Händler</span></div><div class="admin-stat-card"><strong>${s.orders||0}</strong><span>Bestellungen</span></div><div class="admin-stat-card"><strong>${adminMoney(s.revenue)}</strong><span>Umsatz</span></div><div class="admin-stat-card"><strong>${adminMoney(s.commission)}</strong><span>Provision</span></div><div class="admin-stat-card"><strong>${adminMoney(s.pending_payouts)}</strong><span>Offene Auszahlungen</span></div>`;admin$('#merchantTotal').textContent=`${(merchants||[]).length} Händler`;admin$('#adminOrderTotal').textContent=`${(orders||[]).length} Bestellungen`;
admin$('#merchantTable').innerHTML=(merchants||[]).map(m=>`<div class="admin-table-row"><div><strong>${adminEsc(m.shop_name)}</strong><span>${adminEsc(m.owner_name||'Händler')} · ${adminEsc(m.status)}</span></div><div class="admin-merchant-actions"><strong>${Number(m.commission_rate).toFixed(1)}%</strong><small>Provision</small><select data-merchant-status="${adminEsc(m.id)}"><option value="pending" ${m.status==='pending'?'selected':''}>Ausstehend</option><option value="approved" ${m.status==='approved'?'selected':''}>Freigegeben</option><option value="rejected" ${m.status==='rejected'?'selected':''}>Abgelehnt</option><option value="suspended" ${m.status==='suspended'?'selected':''}>Gesperrt</option></select></div></div>`).join('')||'<p class="muted">Noch keine Händler.</p>';
admin$('#merchantTable').querySelectorAll('[data-merchant-status]').forEach(el=>el.addEventListener('change',()=>updateMerchantStatus(el.dataset.merchantStatus,el.value)));
admin$('#adminOrderTable').innerHTML=(orders||[]).slice(0,20).map(o=>`<div class="admin-table-row"><div><strong>#${o.id}</strong><span>${adminEsc(o.status)} · ${new Date(o.created_at).toLocaleDateString('de-DE')}</span></div><div><strong>${adminMoney(o.total)}</strong><small>Provision ${adminMoney(o.commission_amount)}</small></div></div>`).join('')||'<p class="muted">Noch keine Bestellungen.</p>';
admin$('#payoutTable').innerHTML=(payouts||[]).slice(0,20).map(p=>`<div class="admin-table-row"><div><strong>Händler #${String(p.merchant_id).slice(0,8)}</strong><span>${new Date(p.created_at).toLocaleDateString('de-DE')}</span></div><div><strong>${adminMoney(p.amount)}</strong><small>${adminEsc(p.status)}</small></div></div>`).join('')||'<p class="muted">Noch keine Auszahlungen.</p>';
admin$('#adminSystem').innerHTML=`<div><span>Angemeldet</span><strong>${adminEsc(adminUser.email||'')}</strong></div><div><span>Admin</span><strong>Aktiv</strong></div><div><span>Zeitraum</span><strong>${admin$('#adminPeriod').selectedOptions[0].textContent}</strong></div><div><span>Bereitgestellte Provisionen</span><strong>${adminMoney(s.commission)}</strong></div>`}
async function updateMerchantStatus(id,status){if(!adminIsAdmin)return;const {error}=await adminDb.from('merchants').update({status}).eq('id',id);if(error){notifyAdmin(error.message);return}notifyAdmin(status==='approved'?'Händler freigegeben':status==='rejected'?'Händler abgelehnt':status==='suspended'?'Händler gesperrt':'Händler auf ausstehend gesetzt');await loadAdminStats()}
async function saveCommission(){if(!adminIsAdmin)return;const input=admin$('#defaultCommission');const rate=Number(input.value);if(!Number.isFinite(rate)||rate<0||rate>100)return notifyAdmin('Provision muss zwischen 0 und 100 % liegen');const {data,error}=await adminDb.rpc('admin_set_default_commission',{p_rate:rate});if(error){notifyAdmin(error.message);return}input.value=String(Number(data));notifyAdmin(`Provisionssatz ${Number(data).toFixed(1)} % gespeichert`);await loadCommissionSetting();await loadAdminStats()}
function switchToAdmin(){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));admin$('#adminView')?.classList.remove('hidden');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));admin$('#adminNavBtn')?.classList.add('active');checkAdmin().then(ok=>{if(ok)loadAdminStats()})}
admin$('#adminNavBtn')?.addEventListener('click',switchToAdmin);admin$('#refreshAdmin')?.addEventListener('click',loadAdminStats);admin$('#adminPeriod')?.addEventListener('change',loadAdminStats);admin$('#saveCommission')?.addEventListener('click',saveCommission);adminDb.auth.onAuthStateChange(()=>setTimeout(checkAdmin,0));checkAdmin();